[workspace]
members = [
    "crates/admin-dashboard",
    "crates/customer-portal",
    "crates/desktop",
    "crates/mobile",
    "crates/rpc",
    "crates/ui",
    "crates/ui2",
]
resolver = "2"

[workspace.dependencies]
dioxus = { version = "0.6.0-alpha.5" }
